### PR TITLE
replace js and css with a build from current tauCharts repo

### PR DESCRIPTION
**Pull request by timelyportfolio**
Ok, so the build on the CDN is out-of-date.  After suffering through all the `npm`, `bower`, and `grunt` I could bear, I emerged with the most current CSS and JS for `tauCharts`.  I replaced the dependencies, and the tooltip now works.

P.S.  I hope it is ok, but I left some commented lines in the `yaml` for the non-min version in case we need to debug down the road.

``` r
tauchart(car_dat) %>%
  tau_point( "power", "co2", color = "euroEco" ) %>%
  tau_legend( ) %>%
  tau_tooltip( )
```

image

### CODE REVIEW

**Comment by hrbrmstr** [comment]
this is like record-time for a pretty much fully functional widget :-)

**Comment by timelyportfolio** [comment]
lots of practice between the two of us and a very clean and well-documented API from tauCharts.

**Comment by hrbrmstr** [comment]
wow, they're pretty, too!

**Comment by timelyportfolio** [comment]
What about the `trendlines`?  I guess why not.

**Comment by hrbrmstr** [comment]
aye. agreed. but you should take a break. i need to finish cooking dinner :-)

**Comment by hrbrmstr** [comment]
just updated Rpubs, README & DESCRIPTION

**Pull request merged**
