### PR TITLE
remove dependency on xts

### PR DESCRIPTION
**Pull request by timelyportfolio**
I believe these couple of simple changes will remove the dependency on `xts`.  Guess we'll see come CRAN check time.

### CODE REVIEW

**Comment by hrbrmstr** [comment]
So, the following seem to be missing (the tauCharts.js and plugins/…)

```
script: #tauCharts.min.js
  - tauCharts.js
  - plugins/tauCharts.tooltip.js
  - plugins/tauCharts.legend.js
```

**Comment by timelyportfolio** [comment]
Oh dang, I thought I ignored those changes while testing.  Argh, sorry; will pull

**Comment by timelyportfolio** [comment]
done in #13; sorry

**Comment by timelyportfolio** [comment]
one plus, tooltips work with dates also.

**Comment by timelyportfolio** [comment]
went ahead and merged

**Pull request merged**
